version: '3.4'

services:
  guestbook-express:
    image: ${REGISTRY_NAME}.azurecr.io/guestbook-express:1.0.0
    build: .
    environment:
      NODE_ENV: production
      PORT: 5001
    ports:
      - 5001

  redis:
    image: redis:6-buster
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - guestbook-express-redis-data:/data

volumes:
  guestbook-express-redis-data:
    driver: azure_file
    driver_opts:
      share_name: guestbook-express-redis-data
      storage_account_name: ${STORAGE_ACCOUNT_NAME}

